export const IMAGE_VALIDATED = "IMAGE_VALIDATED";
export const IMAGE_NOT_VALIDATED = "IMAGE_NOT_VALIDATED";
export const IMAGE_PROCESSED = "IMAGE_PROCESSED";
export const IMAGE_NOT_PROCESSED = "IMAGE_NOT_PROCESSED"
